// ============================================================
// ARCILLA HECHIZADA — catálogo universal + carrito
// ============================================================
let PRODUCTOS = [], PIEZAS_UNICAS = [], OPINIONES = [], FAQ = [];
const WHATSAPP='34722379095', EMAIL='arcillahechizada@gmail.com', CART_KEY='arcillaHechizadaCarrito';

const GITHUB_REPO='arcillahechizada/arcilla-hechizada-web';
async function cargarCarpetaProductosGitHub(folder){
  const api=`https://api.github.com/repos/${GITHUB_REPO}/contents/${folder}?ref=main`;
  const r=await fetch(api,{cache:'no-store',headers:{'Accept':'application/vnd.github+json'}});
  if(!r.ok) throw new Error('No se pudo leer '+folder);
  const files=await r.json();
  const jsons=Array.isArray(files)?files.filter(f=>f.type==='file'&&/\.json$/i.test(f.name)):[];
  const datos=await Promise.all(jsons.map(async f=>{
    const rr=await fetch(f.download_url+`?t=${Date.now()}`,{cache:'no-store'});
    if(!rr.ok) return null;
    try{return await rr.json();}catch(e){return null;}
  }));
  return datos.filter(Boolean);
}
async function cargarDatos(){
  const [productosFallback,piezas,opiniones,faq]=await Promise.all([
    fetch('data/productos.json',{cache:'no-store'}).then(r=>r.ok?r.json():{productos:[]}).catch(()=>({productos:[]})),
    fetch('data/piezas-unicas.json',{cache:'no-store'}).then(r=>r.ok?r.json():{piezas:[]}).catch(()=>({piezas:[]})),
    fetch('data/opiniones.json',{cache:'no-store'}).then(r=>r.ok?r.json():{opiniones:[]}).catch(()=>({opiniones:[]})),
    fetch('data/faq.json',{cache:'no-store'}).then(r=>r.ok?r.json():{faq:[]}).catch(()=>({faq:[]}))
  ]);
  try{
    const [generales,infusiones,inciensos]=await Promise.all([
      cargarCarpetaProductosGitHub('data/productos'),
      cargarCarpetaProductosGitHub('data/infusiones'),
      cargarCarpetaProductosGitHub('data/inciensos')
    ]);
    infusiones.forEach(p=>p.categoria='infusiones');
    inciensos.forEach(p=>p.categoria='inciensos');
    PRODUCTOS=[...generales,...infusiones,...inciensos];
  }catch(e){
    PRODUCTOS=Array.isArray(productosFallback.productos)?productosFallback.productos:[];
  }
  PRODUCTOS.sort(ordenProductos);
  PIEZAS_UNICAS=Array.isArray(piezas.piezas)?piezas.piezas:[]; OPINIONES=Array.isArray(opiniones.opiniones)?opiniones.opiniones:[]; FAQ=Array.isArray(faq.faq)?faq.faq:[]; actualizarContadorCarrito();
}
function ordenProductos(a,b){
  const oa=Number.isFinite(Number(a.orden))?Number(a.orden):999999;
  const ob=Number.isFinite(Number(b.orden))?Number(b.orden):999999;
  if(oa!==ob)return oa-ob;
  return String(a.nombre||'').localeCompare(String(b.nombre||''),'es',{sensitivity:'base'});
}
function escHTML(v=''){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function texto(v=''){return escHTML(v).replace(/\n/g,'<br>');}
function precioNumero(p){const n=Number(p?.precio);return Number.isFinite(n)?n:0;}
function precioTexto(p){return Number.isFinite(Number(p?.precio))?`${Number(p.precio).toFixed(2).replace('.',',')} €`:'Consultar';}
function bool(v){return v===true||v==='true';}
function etiquetaEstado(e){return ({disponible:'Disponible',bajo_pedido:'Bajo pedido',agotado:'Agotado',vendido:'Vendido',reservada:'Reservada',vendida:'Vendida',oculto:'No publicado'})[e]||e||'';}
function imagenProducto(p){return p.imagenPrincipal||(Array.isArray(p.galeria)&&p.galeria[0])||'';}
function bloqueSinFoto(){return '<div class="foto-pendiente">Fotografía pendiente</div>';}
function tarjetaProductoHTML(p){const est=etiquetaEstado(p.estado);return `<a class="tarjeta-producto" href="ficha.html?id=${encodeURIComponent(p.id)}"><div class="foto imagen-tarjeta">${imagenProducto(p)?`<img src="${escHTML(imagenProducto(p))}" alt="${escHTML(p.nombre||'Producto')}" loading="lazy">`:bloqueSinFoto()}${est?`<span class="etiqueta ${['vendido','vendida'].includes(p.estado)?'etiqueta-vendida':'etiqueta-disponible'}">${escHTML(est)}</span>`:''}</div><div class="info info-tarjeta"><h3>${escHTML(p.nombre||'Producto')}</h3><p class="precio">${precioTexto(p)}</p>${p.descripcionCorta?`<p>${texto(p.descripcionCorta)}</p>`:''}</div></a>`;}
function renderCategoria(id,cat){const c=document.getElementById(id);if(!c)return;const ps=PRODUCTOS.filter(p=>p.categoria===cat&&p.estado!=='oculto'&&p.coleccion!=='linea_efecto_piedra').sort(ordenProductos);c.innerHTML=ps.length?ps.map(tarjetaProductoHTML).join(''):'<p class="aviso-pendiente">Todavía no hay productos publicados en esta categoría.</p>';}
function renderColeccion(id,coleccion){const c=document.getElementById(id);if(!c)return;const ps=PRODUCTOS.filter(p=>p.coleccion===coleccion&&p.estado!=='oculto').sort(ordenProductos);c.innerHTML=ps.length?ps.map(tarjetaProductoHTML).join(''):'<p class="aviso-pendiente">Todavía no hay productos publicados en esta colección.</p>';}
function renderPiezasUnicas(id){const c=document.getElementById(id);if(!c)return;c.innerHTML=PIEZAS_UNICAS.filter(p=>p.estado!=='oculto').map(tarjetaProductoHTML).join('');}
function youtubeEmbed(url){if(!url)return'';const m=String(url).match(/(?:youtube\.com\/(?:watch\?v=|embed\/|shorts\/)|youtu\.be\/)([A-Za-z0-9_-]{6,})/);return m?`<div class="video-ficha"><iframe src="https://www.youtube.com/embed/${m[1]}" title="Vídeo del producto" loading="lazy" allowfullscreen></iframe></div>`:`<p><a class="btn btn-secundario" href="${escHTML(url)}" target="_blank" rel="noopener">Ver vídeo</a></p>`;}
function imagenes(p){const a=[];[imagenProducto(p)].concat(Array.isArray(p.galeria)?p.galeria:[]).forEach(x=>{if(x&&!a.includes(x))a.push(x);});return a;}
function galeriaHTML(p){const fs=imagenes(p);return `<div class="galeria-producto"><div class="foto-principal">${fs.length?`<img id="foto-principal-ficha" src="${escHTML(fs[0])}" alt="${escHTML(p.nombre||'Producto')}">`:bloqueSinFoto()}</div>${fs.length>1?`<div class="galeria-miniaturas">${fs.map((f,i)=>`<img class="miniatura ${i?'':'activa'}" src="${escHTML(f)}" alt="Foto ${i+1}" data-foto="${escHTML(f)}" loading="lazy">`).join('')}</div>`:''}${p.video?youtubeEmbed(p.video):''}</div>`;}
function parrafos(v){return String(v||'').split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);}
function detalleDesplegable(titulo,contenido,clase=''){if(!contenido)return'';return `<details class="ficha-acordeon ${clase}"><summary>${escHTML(titulo)}</summary><div class="acordeon-contenido">${texto(contenido)}</div></details>`;}
function descripcionConLeerMas(v){const ps=parrafos(v);if(!ps.length)return'';if(ps.length===1)return `<section class="ficha-detalle"><h3>Descripción</h3><p>${texto(ps[0])}</p></section>`;return `<section class="ficha-detalle"><h3>Descripción</h3><p>${texto(ps[0])}</p><details class="leer-mas"><summary>Leer más</summary><div class="acordeon-contenido">${ps.slice(1).map(x=>`<p>${texto(x)}</p>`).join('')}</div></details></section>`;}
function normalizarLista(a){if(!Array.isArray(a))return[];return a.map(x=>typeof x==='string'?{nombre:x.trim(),valor:x.trim()}:{nombre:String(x.nombre||x.color||x.titulo||x.valor||'Opción').trim(),valor:String(x.valor||x.nombre||x.color||x.titulo||'Opción').trim()});}
function opcionesProducto(p){const out=[];if(bool(p.personalizable)){let h='<section class="opciones-ficha"><h3>Personalización</h3>';if(p.opcionesPersonalizacion)h+=`<p>${texto(p.opcionesPersonalizacion)}</p>`;const sels=Array.isArray(p.opcionesPersonalizacionCliente)?p.opcionesPersonalizacionCliente:[];if(bool(p.activarSelectorPersonalizacion)&&sels.length)sels.forEach((s,i)=>{const os=normalizarLista(s.opciones);if(!os.length)return;h+=`<div class="campo-opcion"><label for="personalizacion-${i}">${escHTML(s.nombre||'Elige una opción')}</label><select id="personalizacion-${i}" data-tipo="personalizacion" data-label="${escHTML(s.nombre||'Personalización')}">${os.map(o=>`<option value="${escHTML(o.valor)}">${escHTML(o.nombre)}</option>`).join('')}</select></div>`;});h+='</section>';out.push(h);}
if(bool(p.mostrarVariantes)){const vs=Array.isArray(p.variantes)?p.variantes.filter(v=>v&&v.disponible!==false&&v.disponible!=='false'):[];if(vs.length)out.push(`<section class="opciones-ficha"><h3>Variantes / colores</h3><div class="campo-opcion"><label for="select-variante">Elige tu opción</label><select id="select-variante" data-tipo="variante" data-label="Color / variante">${vs.map(v=>`<option value="${escHTML(v.color||v.nombre||'')}">${escHTML(v.color||v.nombre||'Variante')}</option>`).join('')}</select></div></section>`);}
if(bool(p.mostrarCollarLlavero)){let fs=normalizarLista(p.formatosDisponibles);if(!fs.length)fs=[{nombre:'Collar',valor:'Collar'},{nombre:'Llavero',valor:'Llavero'}];out.push(`<section class="opciones-ficha"><h3>Formato</h3><div class="campo-opcion"><label for="select-formato">¿Cómo lo quieres?</label><select id="select-formato" data-tipo="formato" data-label="Formato">${fs.map(o=>`<option value="${escHTML(o.valor)}">${escHTML(o.nombre)}</option>`).join('')}</select></div></section>`);}
if(bool(p.permiteOtroColor))out.push(`<section class="opciones-ficha"><h3>Otro color</h3><p>Puedes solicitar otro color aunque no aparezca entre las fotografías.</p><div class="campo-opcion"><label for="input-otro-color">Color que te gustaría</label><input id="input-otro-color" data-tipo="otro-color" data-label="Otro color" type="text" placeholder="Escribe aquí el color"></div></section>`);return out.join('');}
function opcionesSeleccionadas(){const d={};document.querySelectorAll('#ficha-contenido select[data-tipo],#ficha-contenido input[data-tipo]').forEach(e=>{const v=(e.value||'').trim();if(v)d[e.dataset.label||'Opción']=v;});return d;}
function mensajeConsulta(p){const o=opcionesSeleccionadas();let m=`Hola, me gustaría consultar/pedir este producto de Arcilla Hechizada:\n\n${p.nombre} — ${precioTexto(p)}`;Object.entries(o).forEach(([k,v])=>m+=`\n${k}: ${v}`);if(p.estado==='bajo_pedido')m+='\n\nSé que este producto es bajo pedido.';return m;}
function actualizarPedido(){const p=window.PRODUCTO_ACTUAL;if(!p)return;const m=mensajeConsulta(p),wa=document.getElementById('btn-wa'),em=document.getElementById('btn-email');if(wa)wa.href=`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(m)}`;if(em)em.href=`mailto:${EMAIL}?subject=${encodeURIComponent('Consulta sobre '+p.nombre)}&body=${encodeURIComponent(m)}`;}
function itemCarrito(p,o){return{key:p.id+'::'+JSON.stringify(o||{}),id:p.id,nombre:p.nombre,precio:precioNumero(p),imagen:imagenProducto(p),opciones:o||{},cantidad:1,pagos:Array.isArray(p.formasPagoDisponibles)?p.formasPagoDisponibles.filter(Boolean):[]};}
function leerCarrito(){try{const c=JSON.parse(localStorage.getItem(CART_KEY)||'[]');return Array.isArray(c)?c:[];}catch(e){return[];}}
function guardarCarrito(c){localStorage.setItem(CART_KEY,JSON.stringify(c));actualizarContadorCarrito();}
function actualizarContadorCarrito(){const n=leerCarrito().reduce((s,i)=>s+(Number(i.cantidad)||0),0);document.querySelectorAll('#contador-carrito').forEach(e=>e.textContent=n);}
function añadirAlCarrito(p,o,cantidad=1){const c=leerCarrito(),it=itemCarrito(p,o),old=c.find(x=>x.key===it.key);if(old)old.cantidad+=cantidad;else{it.cantidad=cantidad;c.push(it);}guardarCarrito(c);mostrarAvisoCarrito('Producto añadido al carrito.');}
function mostrarAvisoCarrito(t){let a=document.getElementById('aviso-carrito');if(!a){a=document.createElement('div');a.id='aviso-carrito';a.className='aviso-carrito';document.body.appendChild(a);}a.textContent=t;a.classList.add('visible');clearTimeout(window._aviso);window._aviso=setTimeout(()=>a.classList.remove('visible'),2400);}
function sePuedeComprar(p){return bool(p.activarCompra)&&!['agotado','vendido','vendida','reservada','oculto'].includes(p.estado)&&Number.isFinite(Number(p.precio));}
function accionesCompra(p){if(!sePuedeComprar(p))return '';const cantidad=(p.categoria==='infusiones'||p.categoria==='inciensos')?`<div class="cantidad-ficha"><span>Cantidad</span><button type="button" id="cantidad-menos">−</button><strong id="cantidad-valor">1</strong><button type="button" id="cantidad-mas">+</button></div>`:'';return `${cantidad}<div class="ficha-botones ficha-botones-tienda"><button id="btn-carrito" class="btn btn-carrito" type="button">Añadir al carrito</button><a id="btn-wa" href="#" class="btn btn-whatsapp-producto" target="_blank" rel="noopener">WhatsApp · dudas / personalizar</a><a id="btn-email" href="#" class="btn btn-secundario">Enviar correo</a></div>`;}
function fichaEspecial(p){if(p.categoria==='infusiones'){return `${descripcionConLeerMas(p.descripcionCompleta||p.descripcion)}${detalleDesplegable('Modo de empleo',p.modoEmpleo)}${detalleDesplegable('Ingredientes',p.ingredientes)}${p.medidas?`<section class="ficha-detalle"><h3>Cantidad / formato</h3><p>${texto(p.medidas)}</p></section>`:''}`;}
if(p.categoria==='inciensos'){return `${descripcionConLeerMas(p.descripcionCompleta||p.descripcion)}${detalleDesplegable('Notas olfativas',p.notasOlfativas)}${detalleDesplegable('Modo de uso',p.modoUso)}${detalleDesplegable('Características',p.caracteristicas)}${detalleDesplegable('Ingredientes',p.ingredientes)}${p.medidas?`<section class="ficha-detalle"><h3>Cantidad / formato</h3><p>${texto(p.medidas)}</p></section>`:''}`;}
return `${descripcionConLeerMas(p.descripcionCompleta||p.descripcion)}${detalleDesplegable('Simbolismo y uso',p.simbolismo||p.simbolismoUso)}${detalleDesplegable('Materiales',p.materiales)}${p.medidas?`<section class="ficha-detalle"><h3>Medidas</h3><p>${texto(p.medidas)}</p></section>`:''}${detalleDesplegable('Cuidados',p.cuidados)}${p.elaboracion?`<section class="ficha-detalle"><h3>Elaboración</h3><p>${texto(p.elaboracion)}</p></section>`:''}`;}
function renderFicha(){const id=new URLSearchParams(location.search).get('id')||new URLSearchParams(location.search).get('producto'),c=document.getElementById('ficha-contenido');if(!c)return;if(!id){c.innerHTML='<p class="aviso-pendiente">No se ha indicado ningún producto.</p>';return;}const p=PRODUCTOS.find(x=>x.id===id)||PIEZAS_UNICAS.find(x=>x.id===id);if(!p||p.estado==='oculto'){c.innerHTML='<p class="aviso-pendiente">Este producto todavía no está publicado.</p>';return;}window.PRODUCTO_ACTUAL=p;document.title=`${p.nombre||'Producto'} — Arcilla Hechizada`;const est=etiquetaEstado(p.estado),comprable=sePuedeComprar(p);c.innerHTML=`<article class="ficha-producto ficha-universal">${galeriaHTML(p)}<div class="detalles-ficha"><span class="eyebrow">${escHTML(p.categoria||'Pieza artesanal')}</span><h1>${escHTML(p.nombre||'Producto')}</h1><div class="estado-ficha"><span class="etiqueta ${['vendido','vendida'].includes(p.estado)?'etiqueta-vendida':'etiqueta-disponible'}">${escHTML(est)}</span></div><p class="ficha-precio">${precioTexto(p)}</p>${fichaEspecial(p)}${opcionesProducto(p)}${accionesCompra(p)}${!comprable?'<p class="aviso-pendiente aviso-no-compra">Este producto no está disponible para compra online en este momento.</p>':''}</div></article>`;
 c.querySelectorAll('.miniatura').forEach(m=>m.addEventListener('click',()=>{const im=c.querySelector('#foto-principal-ficha');if(im)im.src=m.dataset.foto;c.querySelectorAll('.miniatura').forEach(x=>x.classList.remove('activa'));m.classList.add('activa');}));
 if(comprable){let cantidad=1;const cv=c.querySelector('#cantidad-valor');const menos=c.querySelector('#cantidad-menos');const mas=c.querySelector('#cantidad-mas');if(cv&&menos&&mas){menos.addEventListener('click',()=>{cantidad=Math.max(1,cantidad-1);cv.textContent=cantidad;});mas.addEventListener('click',()=>{cantidad++;cv.textContent=cantidad;});}document.getElementById('btn-carrito').addEventListener('click',()=>añadirAlCarrito(p,opcionesSeleccionadas(),cantidad));document.querySelectorAll('#ficha-contenido select[data-tipo],#ficha-contenido input[data-tipo]').forEach(e=>{e.addEventListener('change',actualizarPedido);e.addEventListener('input',actualizarPedido);});actualizarPedido();}
}
function calcularEnvio(cp){const s=String(cp||'').replace(/\D/g,'');if(!/^\d{5}$/.test(s))return null;const pref=Number(s.slice(0,2));if([35,38,51,52].includes(pref))return 7.50;return 6.50;}
function metodosPagoCarrito(c){const listas=c.map(i=>Array.isArray(i.pagos)&&i.pagos.length?i.pagos:['Bizum','PayPal','Efectivo']);if(!listas.length)return['Bizum','PayPal','Efectivo'];const inter=listas.reduce((a,b)=>a.filter(x=>b.includes(x)),listas[0].slice());return inter.length?inter:[...new Set(listas.flat())];}
function renderCarrito(){const root=document.getElementById('carrito-contenido');if(!root)return;let c=leerCarrito();if(!c.length){root.innerHTML='<div class="carrito-vacio"><h1>Tu carrito está vacío</h1><p>Cuando encuentres algo que quieras conservar, añádelo aquí.</p><a class="btn btn-primario" href="tienda.html#categorias-tienda">Explorar la tienda</a></div>';return;}const sub=()=>c.reduce((s,i)=>s+(Number(i.precio)||0)*(Number(i.cantidad)||1),0),pagos=metodosPagoCarrito(c);
function pintar(){const subtotal=sub(),cp=document.getElementById('cp-envio')?.value||'',env=calcularEnvio(cp),total=env===null?subtotal:subtotal+env;root.innerHTML=`<div class="carrito-layout"><section class="carrito-ticket"><div class="ticket-cabecera"><span>Arcilla Hechizada</span><span>Tu pedido</span></div><div class="carrito-items">${c.map((i,idx)=>`<div class="carrito-item"><a class="carrito-item-foto carrito-enlace-producto" href="ficha.html?id=${encodeURIComponent(i.id)}" title="Volver al producto">${i.imagen?`<img src="${escHTML(i.imagen)}" alt="${escHTML(i.nombre)}">`:'✦'}</a><div class="carrito-item-info"><a class="carrito-producto-enlace" href="ficha.html?id=${encodeURIComponent(i.id)}"><h3>${escHTML(i.nombre)}</h3></a>${Object.entries(i.opciones||{}).map(([k,v])=>`<small>${escHTML(k)}: ${escHTML(v)}</small>`).join('')}<strong>${(Number(i.precio)||0).toFixed(2).replace('.',',')} €</strong></div><div class="carrito-cantidad"><button type="button" data-action="menos" data-i="${idx}">−</button><span>${i.cantidad}</span><button type="button" data-action="mas" data-i="${idx}">+</button></div><button type="button" class="carrito-eliminar" data-action="eliminar" data-i="${idx}">Eliminar</button></div>`).join('')}</div><div class="ticket-linea"><span>Subtotal</span><strong>${subtotal.toFixed(2).replace('.',',')} €</strong></div><div class="ticket-linea envio-linea"><span>Gastos de envío</span><strong>${env===null?'Se calcularán':env.toFixed(2).replace('.',',')+' €'}</strong></div><div class="ticket-total"><span>TOTAL</span><strong>${total.toFixed(2).replace('.',',')} €</strong></div></section><aside class="carrito-pago"><h2>Finalizar pedido</h2><label for="cp-envio">Código postal</label><input id="cp-envio" inputmode="numeric" maxlength="5" placeholder="Introduce tu código postal" value="${escHTML(cp)}"><p class="ayuda-cp">Introduce el código postal de entrega para calcular los gastos de envío.</p><button id="btn-pagar" class="btn btn-pagar" type="button">PAGAR</button><label for="metodo-pago" class="label-pago">Forma de pago</label><select id="metodo-pago">${pagos.map(p=>`<option>${escHTML(p)}</option>`).join('')}</select><p class="aviso-envio">Aviso: los gastos de envío se calculan según el código postal. Envíos desde <strong>4,50 €</strong> con <span class="marca-correos">Correos</span>. Más información en <a href="envios-y-recogida.html">Preguntas y Envíos</a>.</p><p class="aviso-envio">El pago se gestiona contigo por WhatsApp según la forma de pago que elijas. También puedes consultar cualquier duda antes de confirmar.</p></aside></div>`;
root.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.i),a=b.dataset.action;if(a==='mas')c[i].cantidad++;if(a==='menos')c[i].cantidad=Math.max(1,c[i].cantidad-1);if(a==='eliminar')c.splice(i,1);guardarCarrito(c);pintar();}));
const inp=document.getElementById('cp-envio');const update=()=>{const e=calcularEnvio(inp.value),line=root.querySelector('.envio-linea strong'),tot=root.querySelector('.ticket-total strong');if(line)line.textContent=e===null?'Se calcularán':e.toFixed(2).replace('.',',')+' €';if(tot)tot.textContent=(subtotal+(e||0)).toFixed(2).replace('.',',')+' €';};inp.addEventListener('input',update);
document.getElementById('btn-pagar').addEventListener('click',()=>{const cpv=inp.value.trim(),env2=calcularEnvio(cpv);if(env2===null){alert('Introduce un código postal válido de 5 cifras para calcular el envío.');return;}const metodo=document.getElementById('metodo-pago').value,st=subtotal(),tot=st+env2;let m='Hola, quiero realizar este pedido en Arcilla Hechizada:\n\n';c.forEach(i=>{m+=`${i.nombre} × ${i.cantidad} = ${(i.precio*i.cantidad).toFixed(2).replace('.',',')} €\n`;Object.entries(i.opciones||{}).forEach(([k,v])=>m+=`  ${k}: ${v}\n`);});m+=`\nSUBTOTAL: ${st.toFixed(2).replace('.',',')} €\nGASTOS DE ENVÍO: ${env2.toFixed(2).replace('.',',')} €\nTOTAL: ${tot.toFixed(2).replace('.',',')} €\n\nCódigo postal de entrega: ${cpv}\nForma de pago elegida: ${metodo}\n\nQuedo a la espera de tus indicaciones para realizar el pago.`;const url=`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(m)}`;const nueva=window.open(url,'_blank','noopener,noreferrer');if(!nueva){window.location.assign(url);}});}
pintar();}
